### ISSUE TITLE
handling of pre-release versions in `version` command

### ISSUE THREAD

**Issue by bastidest** [qoomon/git-conventional-commits#100]
I was looking up the proper way of doing pre-release versions according to [SemVer item 10](https://semver.org/spec/v2.0.0.html#spec-item-10).

#### Current State
1. Currently the git tags are parsed for strings that **contain** a `major.minor.patch`. Which means `foobar1.2.3asd` successfully parses to `1.2.3`, but does not fit the SemVer specification
https://github.com/qoomon/git-conventional-commits/blob/53ab17fa4ddfe8dddfbf6933c9687215e35ddc2b/lib/commands/config.js#L92
2. Versions containing pre-release information (e.g. `1.2.3-alpha`) are treated as proper releases (i.e. `1.2.3`). Calling the `version` command for a patch change in the example will result in the `1.2.3` version

#### Suggestions
1. I think that the SemVer should be matched according to the [official regex](https://semver.org/spec/v2.0.0.html#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) provided on the SemVer specification (+ optional `v` prefix). Invalid versions should be ignored. 
2. Pre-release versions should be completely ignored when calculating the next version in the `version` command

#### Examples
```
tags: 1.0.0, 2.0.0, 2.0.1-alpha
changes: patch
expected version: 2.0.1
actual version: 2.0.2
---
tags: 1.0.0, 2.0.0, 5.0.0-rc1
changes: minor
expected version: 2.1.0
actual version: 5.1.0
```

What are your thoughts on this? I'd be happy to contribute the necessary changes.

**Comment by qoomon** [comment]
Hi, I understand your first example however I don't understand your second one. From my understanding the expected version should be 5.0.0 alike the first example.

**Comment by bastidest** [comment]
The second example is supposed to show that the pre-release versions are completely ignored when calculating what the next version should be. In the example the last valid non pre-release is `2.0.0` and there were `minor` changes, so the resulting version is expected to be `2.1.0`.

My point is: The next version should only be dependent on the latest proper release + all the changes that were made after this release. Pre-releases should not be factored into this calculation.

**Comment by qoomon** [comment]
Okay I got your point. Sounds reasonable. I'll will release a new version with that change.
