### ISSUE TITLE
Possible enhancement: automatically copy commit-msg script in hooks directory on init command 

### ISSUE THREAD

**Issue by vbelovitsky** [qoomon/git-conventional-commits#126]
Hello again!)
I'm continuing to explore your tool and I want to suggest a small enhancement to simplify setup workflow.
I use Git Bash to create my repos and it is automatically creates .git/hooks directory and other stuff.
So, it will be easier to setup your tool if **commit-msg** script (from md docs) will be automatically copied to .git/hooks directory (if it exists).
In this case the "default behaviour" could be set up with only one **init** command without other manipulations.

**Comment by vbelovitsky** [comment]
I think user should not make additional explicit call to achieve this.
This logic could be included in `git-conventional-commits init` command.

So, default `commit-hook` will be copied to .git/hooks directory just like default `git-conventional-commits.yaml` to repository root.
And everything will be ready to use just with single command, without manual file creating described in [Setup Manually](https://github.com/qoomon/git-conventional-commits#:~:text=t%20commit%2Dmsg-,Setup%20manually,-Setup%20Commit%20Message)

If .git/hooks directory doesn't exist, you could print some warning/guide message in console.

**Comment by qoomon** [comment]
sounds reasonable, I'll add it

**Comment by qoomon** [comment]
feel free to try version `2.5.0`
