### ISSUE TITLE
Unable to bump major version

### ISSUE THREAD

**Issue by GingerLoaf** [qoomon/git-conventional-commits#136]
I am able to bump my minor version using `feat`, and my patch version using `fix` but the major version is not moving either by `feat!` nor 
```
feat: Did a thing

BREAKING CHANGE: Broke stuff
```

Versions:
- macOS 13.2.1
- npm 9.6.0
- git 2.37.1 (Apple Git-137.1)
- conventional commits: 2.6.3

The spec says that ! and BREAKING CHANGE are supposed to bump the major revision. https://www.conventionalcommits.org/en/v1.0.0/

Any advice?

**Comment by GingerLoaf** [comment]
After doing some debugging, I stumbled upon this bit of code
```
// SemVer 2.0.0 §4: public api should not be considered stable when major version is 0
    if (version.major === 0) {
        // never change major version in development releases
        if (changes.breaking > 0 || changes.features > 0) {
            version.minor++;
            version.patch = 0;
            return;
        }
        if (changes.patches > 0) {
            version.patch++;
            return;
        }
    }
```

I suppose this is fair, given the semver spec. I am going to close this issue... but I think mentioning this somewhere in the docs would be good since it isn't clear that this tool will ignore breaking changes until you tag your first release that is a non-zero major release

**Comment by qoomon** [comment]
@GingerLoaf I would be glad to get an PR

**Comment by bastidest** [comment]
Also see #93

**Comment by GingerLoaf** [comment]
I appreciate it @bastidest… I did not realize this was part of the spec, but it completely makes sense to me.
