### ISSUE TITLE
Changelog does not pass markdown linting rules

### ISSUE THREAD

**Issue by FSeidinger** [qoomon/git-conventional-commits#138]
I'm using [markdownlint](https://github.com/markdownlint/markdownlint) in my projects and currently the generated changelog does not pass the linting rules.

Here is my list of violations:

1. [MD041 - First line in file should be a top level header](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md041---first-line-in-file-should-be-a-top-level-header)
2. [MD022 - Headers should be surrounded by blank lines](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md022---headers-should-be-surrounded-by-blank-lines)
3. [MD047 - File should end with a single newline character](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md047---file-should-end-with-a-single-newline-character)
4. [MD033 - Inline HTML](https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md033---inline-html)

If you would like me to fix it, please give me a note. I've checked the generator code and think I can handle it.

To give you an impression of a changelog that nearly passes the markdown linting rules here is the template:

```markdown
# Releases

## **0.0.1**&emsp;<sub><sup>2023-05-23 (8dcd6827b2e1972014ae6b0c95113285f7ff6119...c5d7853b18d96bb808bd8c1cdc75945791b07fdf)</sup></sub>

### Features

* Projektaufsatz (8dcd6827b2e1972014ae6b0c95113285f7ff6119)
* Erster Inhalt (557e009dabd581e885a913a4f2b781c4c7de242a)
* Prozess zur Erfassung von Dokumenten (ef4514bb61e9bbf0a9e0b33a698707f9306f5454)
* Dokumente in den Posteingang stellen (dda53a12f5d971cdd3501f6c3fa85f8de1f1203e)
* Verschärfung der markdown Regeln (328932ddfd0fb4bd562c9a1647a2c51f653b4055)

&ensp;##### `build`

* Conventional Commits (ca00aff54d0051b762f055042016f0f452dac5f6)

<br>

```
To get rid of the `MD033 - Inline HTML` error, you have to give markdownlint an hint, that you want to disable the rule. You can do this by creating the file `.markdownlint.yaml` in the root of the repository with the following content:

```yaml
default: true

MD033:
  allowed_elements:
    - "br"
    - "sub"
    - "sup"

```

**Comment by qoomon** [comment]
Hi @FSeidinger, thanks for reporting, however I don't like the complaint markdown style. Therefore I 'll close this issue for now.

Anyway I fixed `MD022 - Headers should be surrounded by blank lines`

**Comment by qoomon** [comment]
@FSeidinger maybe supporting different themes would be an option, WDYT

**Comment by FSeidinger** [comment]
I guess that profiles or templates would be a good feature.

The current changelog generator would be the default profile then to have backwards compatible.

Give me some time to think about solutions. I will then come back on that.

**Comment by qoomon** [comment]
@FSeidinger any thoughts so far?
