### ISSUE TITLE
WIP feature not working due to faulty commitIgnoreRegexPattern handling

### ISSUE THREAD

**Issue by FSeidinger** [qoomon/git-conventional-commits#139]
# Description

Currently the `commitIgnoreRegexPattern` does not work as expected. There are x issues with it:

1. The tests call the `commandChangelog` handler with a configuration file path of `./git-conventional-commits.yaml` which is not available in the test context.
2. Therefore the `commandChangelog` handler falls back to the builtin `defaultConfig()` which has in turn `commitIgnoreRegexPattern` set to `null`.
3. The `generateMarkdown` function of the `ChangelogGenerator` has another signature and takes `commitIgnoreRegex` paramter instead of a `commitIgnoreRegexPattern`.
4. The `String.match` function with a regular expression string cannot be uses with the combination of a line beginning pattern and a multiline text, such as the commit subject and it's body is.

# Solution

I will submit a patch for this issue that has the following fixes:

1. The `defaultConfig()` now has a valid `commitIgnoreRegexPattern`, that is the default of the documentation ("^WIP ").
2. The parameter `commitIgnoreRegex` is set to a RegExp taking the configured pattern and having the multiline flag ("m").
3. I added a test for WIP commits.

# Open Issues

I guess that the tests should have an own configuration, maybe per test, to have the correct config needed for the test. I left this open, because I'm not sure what your thoughts are on that topic.

**Comment by qoomon** [comment]
feel free to try version `git-conventional-commits@2.6.5`

**Comment by nhz-io** [comment]
Please tag the repo with `v2.6.5` 
Pinning `pre-commit` hook like this is ugly:
```
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: 091d85d682f8c3648fc34d7de9c4011f394531bf
    hooks:
      - id: conventional-commits
```

**Comment by qoomon** [comment]
oh my bad. it's done `v2.6.5`
