### ISSUE TITLE
Make commit message RegEx configurable

### ISSUE THREAD

**Issue by insurancer591** [qoomon/git-conventional-commits#161]
In our company we have a fixed prefix for our commit messages that is not negotiable. Sadly the commit message RegEx is not configurable so that we can not use the library out of the box. In the code I see that this would be just a small change even though I don't know if there are side effects. I can make the PR ready if this is fine.

https://github.com/qoomon/git-conventional-commits/blob/52b4e6bab1c8f695818ba8ff94f776ff90a3832c/lib/commands/config.js#L24

**Comment by qoomon** [comment]
Sounds good to me. I do not expect any issues with that.

**Comment by qoomon** [comment]
feel free to try version 2.7.0. Just configure `convention.commitMessageRegexPattern` for your use case

**Comment by Mo0rBy** [comment]
@qoomon I think this option needs to be documented in the project README.
I had to come to the issues section to see that it existed.
