### ISSUE TITLE
Breaking changes in git comment footer not working as expected

### ISSUE THREAD

**Issue by eagleyes** [qoomon/git-conventional-commits#79]
Hi , I am not sure if I am doing something wrong her e, but the breaking changes footer are not working as per the conventional BREAKING CHANGES footer addon.

Commit message:
fix: this is a commit message
BREAKING CHANGES: code is not compatible anymore

In the git.js , it is parsing the git log in one line... 
git log --reverse --format=${gitLogFormat} ${from ? `${from}..` : ''}${to}`, {encoding: 'UTF-8'}
this gives me something like:

7234acs234 ===LOG_FIELD_SEPARATOR=== fix: this is a commit message BREAKING CHANGES: code is not compatible anymore ===LOG_FIELD_SEPARATOR===  ...

The subject of the git log command is now a ONE LINER , then the regex to look for a breaking change is not working as per the conventional commits breaking change footer...  (it looks for BREAKING CHNAGE at the beginning of the line , but there is no newline line here , therefore no BREAKING CHANGE at the beginning)

This module does not give me a breaking change if the breaking change comment is not at the beginning of line 1 .

I did not debug this , but I do not get expected result.

thanks

**Comment by eagleyes** [comment]
I have changed one character and it is now working for my goal... not sure if it will break anythign else , but what I have done is replace the %b to %B in the git.js file in the gitLogFormat variable and now all my BREAKING CHNAGES footers are now considered as breaking changes. Will just need to test it properly.

**Comment by qoomon** [comment]
thanks for reporting, I'll have look

**Comment by qoomon** [comment]
I got your issue. This happens because you probably don't have an empty line after the subject, that is why everything is part of the subject and there is no body.

I'm only looking for the `BREAKING CHANGES` within the body.

so instead of `git commit -a -m $'feat: fly to the moon\nBREAKING CHANGES: new fuel'`, you should rather do `git commit -a -m 'feat: fly to the moon' -m 'BREAKING CHANGES: new fuel'` this will automatically adds an empty line and therefore defines the beginning of the body.

**Comment by qoomon** [comment]
Can you confirm if this is the reason?

**Comment by eagleyes** [comment]
ok got it , you are right ... I was using vscode and in vscode in order to get the subject and body split , we need to add an empty line and it is working as intended.

thank you very much for your quick response... this tool is really a life saver for us !!

also tested in eclipse , git GUI for windows , git command and all good now...

**Comment by qoomon** [comment]
Glad to hear that.
